### ISSUE TITLE
Could you also mention Firefox Tampermonkey in readme?

### ISSUE THREAD

**Issue by grayrattus** [cmprmsd/Overleaf-Image-Helper#1]
Hi,
I just noticed that this Tampermonkey addon is also available on Firefox. I tested it and it seems to work fine.
Could you also mention this in the script readme? 

Anyway, great work. Thanks to you I can finally make notes in Overleaf as I previously did in Google Docs.

**Comment by cmprmsd** [comment]
Hey! Sure thing! I tried it on Firefox myself some time ago and had trouble accessing the DOM with it. 
So you do not have any issues? 🤯🥳 

Which version do you use? 

I'll also write a chapter on how to integrate this into the web server of Overleaf community. 

Btw. Are you interested in automatic resizing of the images during the upload? 
I noticed quite a slow down in the compilation time when many photographs get added with high resolution through my script.

**Comment by grayrattus** [comment]
Mozilla Firefox 87.0
Tampermonkey  4.13.6136 2021-04-28
When it comes to the Overleaf version I use the self-hosted docker image of Community Edition.

Everything works without issues.
I also tried to set it up with Greasemonkey addon but it didn't work.

I haven't noticed any compilation slow down but my current document has like 10 images ;) If this automatic resizing does not impact upload performance then I think it would be a cool feature.

**Comment by cmprmsd** [comment]
Alright! Then I must have been using Greasemonkey in my early attempts and switched to Tampermonkey as it was the only tool for Chrome :) 

I'll add some features during the next weekend when I find some time :)

**Comment by AlexBitsTech** [comment]
Hello,
Have you, by any chance, found a way to integrate this directly into your overleaf CE docker container?

**Comment by cmprmsd** [comment]
@AlexBitsTech Yes I did for our company. You'll have to modify files after deploying the container and recompile the web part of the application. It's not supported, but you could open an issue with Overleaf to integrate this feature. :)

I haven't been able to push the changes yet but the issue here is solved with the last commit.
