### ISSUE TITLE
HTTP 422 Unprocessable Content Error

### ISSUE THREAD

**Issue by malekinho8** [cmprmsd/Overleaf-Image-Helper#11]
It seems that the uploadImage function is running into an error at the following line:

```
xhr.onreadystatechange = function () {
```

After that line is executed, the xhr.status variable becomes 422, and the function throws an error. I logged the lines before in the console:

```
        var xhr = new XMLHttpRequest();
        var domain = "https://www.overleaf.com";
        var path = document.location.pathname + "/upload?folder_id=" + _ide.fileTreeManager.findEntityByPath("assets").id + "&_csrf=" + csrfToken;
        var url = path;
        // var url = document.location.pathname + "/upload?folder_id=" + _ide.fileTreeManager.findEntityByPath("assets").id + "&_csrf=" + csrfToken;
        let formData = new FormData();
        formData.append("qqfile", imageBlob, "my_image.png");
        xhr.open("POST", url, true);
        // xhr.setRequestHeader("Content-Type", "application/json");
        console.log('imageBlob:', imageBlob);
        console.log('hash:', hash);
        console.log('url:', url);
        console.log('formData:', formData);
        formData.forEach((value, key) => {
            console.log(key + ': ' + (value instanceof File ? value.name : value));
        });
        console.log(xhr.status)
        xhr.onreadystatechange = function () {
            console.log(xhr.status)
            if (xhr.readyState === 4 && xhr.status === 200) {
                var json = JSON.parse(xhr.responseText);
                console.log(json)
                console.log(json.entity_id + " Asset created :)");
            }
        };
```

And I got this output:

<img width="728" alt="image" src="https://user-images.githubusercontent.com/78977545/233011857-3599a88f-fd83-4177-b10f-0d186c77a13d.png">

I thought it might be server-side, but in the error description it says the client should update the request before sending again:

<img width="616" alt="image" src="https://user-images.githubusercontent.com/78977545/233012075-81b1064e-77ae-4ebe-ac49-19a06948fa31.png">

Any thoughts on how to proceed with this?

**Comment by birdylife** [comment]
I had an Error 422 about 5 days ago, and I tracked it down to a change in how overleaf processes the XHtml request. 
I changed my code of uploadImage() as follows: 

`function uploadImage(imageBlob,hash){

    try{
        var xhr = new XMLHttpRequest();
        var url = document.location.pathname + "/upload?folder_id=" + _ide.fileTreeManager.findEntityByPath("assets").id; //+ "&_csrf=" + csrfToken;
        let formData = new FormData();
        formData.append("targetFolderId", _ide.fileTreeManager.findEntityByPath("assets").id);
        formData.append("name", hash + ".png");
        formData.append("type", "image/png");
        formData.append("qqfile", imageBlob, hash + ".png");
        xhr.open("POST", url, true);
        xhr.setRequestHeader('x-csrf-token', csrfToken);
        //xhr.setRequestHeader("Content-Type", "application/json");
        xhr.onreadystatechange = function () {
            if (xhr.readyState === 4 && xhr.status === 200) {
                var json = JSON.parse(xhr.responseText);
                console.log(json.entity_id + " Asset created :)");
            }
        };
        xhr.send(formData);
    }catch(e)
    {
        console.log(e)
    }

Edit: Struggeling with posting code... 
Hope this helps

**Comment by cmprmsd** [comment]
Just merged an update PR for Code Mirror 6. So the current version of Overleaf should now be fully supported!
