### ISSUE TITLE
breaks with beta version

### ISSUE THREAD

**Issue by cad0p** [cmprmsd/Overleaf-Image-Helper#2]
I just enrolled in overleaf's beta version and it looks like it broke the script

**Comment by cmprmsd** [comment]
Heyhey, yeah they are changing a lot in the upcoming releases and I'll have to implement the feature for the new editor. 

This will only work when I find out the necessary JavaScript functionality that returns the current file, folder and project. 

Feel free to experiment and deliver hints of you find any. I'll come back to this issue later this year when the release happend and I can test it myself. :)

**Comment by cmprmsd** [comment]
Could you point me to the beta release? In the main repo there is a docker-compose setup but this just deploys an old version.

**Comment by cad0p** [comment]
Hi, did you try it out on the public version? (The one available on overleaf.com)

**Comment by cmprmsd** [comment]
They told me there is currently no beta https://github.com/overleaf/overleaf/issues/1031

If the feature set is not important to you, I'd recommend to switch to the prod version. 

When the code mirror 6 update is released, I'll update the script. 😊

**Comment by cad0p** [comment]
That sounds perfect, thanks a lot!

**Comment by cmprmsd** [comment]
Just merged an update PR by @ColinRoitt for Code Mirror 6. So the current version of Overleaf should now be fully supported!
