### ISSUE TITLE
Did the script stop working? 

### ISSUE THREAD

**Issue by przemyslslaw** [cmprmsd/Overleaf-Image-Helper#7]
I've used it for a week or so, but I noticed that it stopped working a few days ago, showing this error in Chrome:

![image](https://user-images.githubusercontent.com/764425/215223193-4a402c16-693b-4230-b330-52de2c11af7a.png)

**Comment by cmprmsd** [comment]
Does it work in the classic editor?

**Comment by przemyslslaw** [comment]
I've switched to "Source (legacy)" mode, refreshed the browser, and indeed the script works fine now.

**Comment by przemyslslaw** [comment]
It doesn't seem to work in "Source" mode, though.

**Comment by cmprmsd** [comment]
Yup. Known issue. I'll fix this when the new editor becomes available in the community edition. 

Closing this issue as it's a duplicate of the other open issue(s).
